### ISSUE TITLE
Roadmap towards CI + notebook

### ISSUE THREAD

**Issue by pangtao22** [pangtao22/quasistatic_simulator#23]
- [x] merge C++ and this repo.
- [x] Write a script that builds the CPP repo and runs all tests. 
- [ ] Use C++ `QuasistaticSimulator` for all but the examples of the ICRA quasistatic simulator paper. 
- [x] Wait for mathematical program to support dual solutions from SOCP solved by SCS.
- [x] All tests should have the option to use free solvers.
